#!/bin/sh

# Create and set directory permissions
mkdir -pv \
	/config/session \
	/config/settings \
	/config/torrents \
	/config/users
chown -R app:app \
	/downloads \
	/config

# Sync the Web root filemount for the HTTP container
/usr/bin/rsync -rptk --delete-before /var/www/rutorrent/ /webroot

# Remove the lockfile if present
if [ -e /config/session/rtorrent.lock ]; then
	rm -v /config/session/rtorrent.lock
fi

# Start the PHP-FPM service
/usr/local/sbin/php-fpm \
	--daemonize \
	--fpm-config /etc/php/rutorrent.conf

# Exec the rtorrent process (not as a child)
exec /usr/bin/rtorrent \
	-n -o import=/etc/rtorrent/rtorrent.rc \
	-i $(wget -qO- http://icanhazip.com/)