version: '2.0'
services:
  application:
    #image: linuxserver/rutorrent:latest
    build:
      context: .
    ports:
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - downloads:/downloads
      - config:/config
      - webroot:/webroot
  client:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - webroot:/var/www/rutorrent
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application
volumes:
  downloads:
  config:
  webroot:
